"""empty message

Revision ID: 0d7ae1acce03
Revises: dfc38fb14df0
Create Date: 2022-12-22 20:15:52.764598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7ae1acce03'
down_revision = 'dfc38fb14df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('ativoId', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('tipoMercado', sa.String(), nullable=True),
    sa.Column('tamanhoLote', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negociacoes')
    # ### end Alembic commands ###
